// <auto-generated />
using System;
using BbfFirmasPoderes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BbfFirmasPoderes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827105626_AddDemoSeed")]
    partial class AddDemoSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DecisionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("details");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation_id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_audit_events_document_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.ToTable("audit_events", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = "ev_0001",
                            Actor = "ana.silva@bbf.com.br",
                            CorrelationId = "corr_a1b2c3",
                            Details = "Upload de contrato-social-acme.pdf (12 páginas, 2.3MB)",
                            DocumentId = "doc_001",
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 4, 29, 14, 22, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "document.uploaded"
                        },
                        new
                        {
                            EventId = "ev_0008",
                            Actor = "system",
                            CorrelationId = "corr_d4e5f6",
                            DecisionId = "dec_002",
                            Details = "Decisão REPROVADO (sócio inativo)",
                            DocumentId = "doc_004",
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 4, 28, 17, 33, 14, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "decision.evaluated"
                        },
                        new
                        {
                            EventId = "ev_0009",
                            Actor = "system",
                            CorrelationId = "corr_g7h8i9",
                            DecisionId = "dec_003",
                            Details = "Decisão MANUAL (baixa confiança)",
                            DocumentId = "doc_003",
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 4, 29, 9, 51, 8, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Type = "decision.evaluated"
                        });
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Decision", b =>
                {
                    b.Property<string>("DecisionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cnpj");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("EvidenciasJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidencias");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string[]>("Motivos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("motivos");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operacao");

                    b.Property<string[]>("SignatariosSolicitados")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("signatarios_solicitados");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("VersionAiModel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version_ai_model");

                    b.Property<string>("VersionAiPrompt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("version_ai_prompt");

                    b.Property<string>("VersionCanonical")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version_canonical");

                    b.Property<string>("VersionRules")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version_rules");

                    b.HasKey("DecisionId");

                    b.HasIndex("Cnpj")
                        .HasDatabaseName("ix_decisions_cnpj");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_decisions_document_id");

                    b.ToTable("decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_decisions_status", "status IN ('APROVADO','REPROVADO','MANUAL')");
                        });

                    b.HasData(
                        new
                        {
                            DecisionId = "dec_001",
                            Cnpj = "12.345.678/0001-90",
                            DocumentId = "doc_001",
                            EvaluatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 14, 25, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EvidenciasJson = "[{\"type\":\"documento\",\"trace\":{\"page\":4,\"offsetStart\":1500,\"offsetEnd\":1750,\"snippet\":\"...acima desse valor, exigir-se-á assinatura conjunta de Diretor e Procurador...\"},\"detalhe\":\"Cláusula 8 do Contrato Social\"},{\"type\":\"fonte_oficial\",\"fonte\":\"Junta Comercial SP\",\"detalhe\":\"Quadro societário consultado em 2026-04-29; ambos os sócios constam como ATIVOS.\"}]",
                            LatencyMs = 1287,
                            Motivos = new[] { "Operação dentro do limite de R$ 500.000 com modo conjunto Diretor + Procurador (Regra RN02 + RN03 v1.2.0).", "Sócios João da Silva e Maria Souza confirmados como ATIVOS na Junta Comercial em 2026-04-29 14:22 UTC.", "Procuração vigente (validFrom 2024-01-01, sem revogação)." },
                            Operacao = "Movimentação financeira — R$ 500.000",
                            SignatariosSolicitados = new[] { "João da Silva (Diretor)", "Maria Souza (Procuradora)" },
                            Status = "APROVADO",
                            VersionAiModel = "gemini-1.5-pro",
                            VersionAiPrompt = "leitura-contrato-social@2.1.0",
                            VersionCanonical = "1.0.0",
                            VersionRules = "1.2.0"
                        },
                        new
                        {
                            DecisionId = "dec_002",
                            Cnpj = "11.222.333/0001-44",
                            DocumentId = "doc_004",
                            EvaluatedAt = new DateTimeOffset(new DateTime(2026, 4, 28, 17, 33, 14, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EvidenciasJson = "[{\"type\":\"fonte_oficial\",\"fonte\":\"Junta Comercial SP\",\"detalhe\":\"Status ATIVO=false desde 2025-09-12\"},{\"type\":\"documento\",\"trace\":{\"page\":2,\"offsetStart\":320,\"offsetEnd\":480,\"snippet\":\"...procuração com validade até 30/08/2025...\"},\"detalhe\":\"Cláusula 3 da Procuração\"}]",
                            LatencyMs = 1542,
                            Motivos = new[] { "Sócio Carlos Pereira consta como INATIVO na Junta Comercial desde 2025-09-12 (Regra RN01 v1.2.0).", "Procuração apresentada está revogada (validTo 2025-08-30)." },
                            Operacao = "Contratação de crédito — R$ 200.000",
                            SignatariosSolicitados = new[] { "Carlos Pereira (Procurador)" },
                            Status = "REPROVADO",
                            VersionAiModel = "gemini-1.5-pro",
                            VersionAiPrompt = "leitura-contrato-social@2.1.0",
                            VersionCanonical = "1.0.0",
                            VersionRules = "1.2.0"
                        },
                        new
                        {
                            DecisionId = "dec_003",
                            Cnpj = "55.666.777/0001-22",
                            DocumentId = "doc_003",
                            EvaluatedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 9, 51, 8, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EvidenciasJson = "[{\"type\":\"documento\",\"trace\":{\"page\":3,\"offsetStart\":800,\"offsetEnd\":1100,\"snippet\":\"...os procuradores poderão, em conjunto ou isoladamente conforme deliberação...\"},\"detalhe\":\"Cláusula ambígua — modo de assinatura não determinístico\"}]",
                            LatencyMs = 1102,
                            Motivos = new[] { "Confiança da extração NER abaixo do threshold (66% < 75%) — Regra de Threshold v1.0.0.", "Cláusula de poderes ambígua na página 3 — recomenda revisão jurídica." },
                            Operacao = "Abertura de conta",
                            SignatariosSolicitados = new[] { "Pedro Henrique (Procurador)" },
                            Status = "MANUAL",
                            VersionAiModel = "gemini-1.5-pro",
                            VersionAiPrompt = "leitura-contrato-social@2.1.0",
                            VersionCanonical = "1.0.0",
                            VersionRules = "1.2.0"
                        });
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Document", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cnpj");

                    b.Property<decimal>("ConfiancaIagen")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confianca_iagen");

                    b.Property<decimal>("ConfiancaNer")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confianca_ner");

                    b.Property<decimal>("ConfiancaOcr")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confianca_ocr");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<int>("Paginas")
                        .HasColumnType("integer")
                        .HasColumnName("paginas");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_path");

                    b.Property<string>("TipoSocietario")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tipo_societario");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DocumentId");

                    b.HasIndex("Cnpj")
                        .HasDatabaseName("ix_documents_cnpj");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_documents_correlation_id");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("ix_documents_file_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_documents_status", "status IN ('pendente','processando_ocr','processando_iagen','processando_ner','canonico_pronto','validacao_oficial','decidido','revisao_humana','falha')");
                        });

                    b.HasData(
                        new
                        {
                            DocumentId = "doc_001",
                            Cnpj = "12.345.678/0001-90",
                            ConfiancaIagen = 0.92m,
                            ConfiancaNer = 0.94m,
                            ConfiancaOcr = 0.97m,
                            CorrelationId = "corr_a1b2c3",
                            FileHash = "a3f2c4...e9d1",
                            FileName = "contrato-social-acme.pdf",
                            Paginas = 12,
                            RazaoSocial = "ACME Indústrias LTDA",
                            Status = "decidido",
                            TipoSocietario = "LTDA",
                            UploadedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 14, 22, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UploadedBy = "ana.silva@bbf.com.br"
                        },
                        new
                        {
                            DocumentId = "doc_004",
                            Cnpj = "11.222.333/0001-44",
                            ConfiancaIagen = 0.93m,
                            ConfiancaNer = 0.95m,
                            ConfiancaOcr = 0.96m,
                            CorrelationId = "corr_d4e5f6",
                            FileHash = "d4e5...0f1a",
                            FileName = "contrato-delta.pdf",
                            Paginas = 6,
                            RazaoSocial = "Delta EIRELI",
                            Status = "decidido",
                            TipoSocietario = "EIRELI",
                            UploadedAt = new DateTimeOffset(new DateTime(2026, 4, 28, 17, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UploadedBy = "joao.t@bbf.com.br"
                        },
                        new
                        {
                            DocumentId = "doc_003",
                            Cnpj = "55.666.777/0001-22",
                            ConfiancaIagen = 0.71m,
                            ConfiancaNer = 0.66m,
                            ConfiancaOcr = 0.78m,
                            CorrelationId = "corr_g7h8i9",
                            FileHash = "c1d2...8e9f",
                            FileName = "procuracao-gama.pdf",
                            Paginas = 4,
                            RazaoSocial = "Gama Investimentos LTDA",
                            Status = "revisao_humana",
                            TipoSocietario = "LTDA",
                            UploadedAt = new DateTimeOffset(new DateTime(2026, 4, 29, 9, 48, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UploadedBy = "ana.silva@bbf.com.br"
                        });
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.KasRun", b =>
                {
                    b.Property<Guid>("KasRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("kas_run_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ExecutionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("execution_id");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("KasRunId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_kas_runs_correlation_id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_kas_runs_document_id");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_kas_runs_execution_id");

                    b.ToTable("kas_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_kas_runs_action", "action IN ('ingest','result')");
                        });

                    b.HasData(
                        new
                        {
                            KasRunId = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000001"),
                            Action = "ingest",
                            CorrelationId = "corr_a1b2c3",
                            DocumentId = "doc_001",
                            DurationMs = 14200,
                            ExecutionId = "exec_acme_001",
                            FileName = "contrato-social-acme.pdf",
                            HttpStatus = 200,
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 4, 29, 14, 22, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Ok = true,
                            PayloadJson = "{\"ok\":true,\"kasStatus\":200,\"action\":\"ingest\",\"correlationId\":\"corr_a1b2c3\",\"executionId\":\"exec_acme_001\",\"fileName\":\"contrato-social-acme.pdf\",\"journey\":\"testes-firmas-e-poderes\",\"mode\":\"sync\",\"body\":{\"status\":\"completed\",\"message\":\"seed ACME doc_001\"}}"
                        });
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("OutboxId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_outbox_document_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_outbox_type");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("person_id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cpf");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nome");

                    b.Property<string>("Qualificacao")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("qualificacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("PersonId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_people_document_id");

                    b.ToTable("people", null, t =>
                        {
                            t.HasCheckConstraint("ck_people_status", "status IN ('ativo','inativo')");
                        });

                    b.HasData(
                        new
                        {
                            PersonId = "p1",
                            Cargo = "Diretor",
                            Cpf = "111.222.***-44",
                            DocumentId = "doc_001",
                            Nome = "João da Silva",
                            Qualificacao = "Sócio-administrador",
                            Status = "ativo"
                        },
                        new
                        {
                            PersonId = "p2",
                            Cargo = "Procuradora",
                            Cpf = "222.333.***-55",
                            DocumentId = "doc_001",
                            Nome = "Maria Souza",
                            Qualificacao = "Sócia",
                            Status = "ativo"
                        },
                        new
                        {
                            PersonId = "p3",
                            Cargo = "Conselheiro",
                            Cpf = "333.444.***-66",
                            DocumentId = "doc_001",
                            Nome = "Carlos Pereira",
                            Qualificacao = "Sócio",
                            Status = "inativo"
                        },
                        new
                        {
                            PersonId = "p4",
                            Cargo = "Procurador",
                            Cpf = "333.444.***-66",
                            DocumentId = "doc_004",
                            Nome = "Carlos Pereira",
                            Qualificacao = "Titular",
                            Status = "inativo"
                        },
                        new
                        {
                            PersonId = "p5",
                            Cargo = "Procurador",
                            Cpf = "444.555.***-77",
                            DocumentId = "doc_003",
                            Nome = "Pedro Henrique",
                            Qualificacao = "Procurador",
                            Status = "ativo"
                        });
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Power", b =>
                {
                    b.Property<string>("PowerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("power_id");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_id");

                    b.Property<string>("LimiteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("limite_currency");

                    b.Property<string>("LimiteExpression")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("limite_expression");

                    b.Property<decimal>("LimiteValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_value");

                    b.Property<int?>("ModoAssinaturaM")
                        .HasColumnType("integer")
                        .HasColumnName("modo_assinatura_m");

                    b.Property<int?>("ModoAssinaturaN")
                        .HasColumnType("integer")
                        .HasColumnName("modo_assinatura_n");

                    b.Property<string[]>("ModoAssinaturaQualificacoes")
                        .HasColumnType("text[]")
                        .HasColumnName("modo_assinatura_qualificacoes");

                    b.Property<string>("ModoAssinaturaTipo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("modo_assinatura_tipo");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operacao");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pessoa");

                    b.Property<int>("SourceOffsetEnd")
                        .HasColumnType("integer")
                        .HasColumnName("source_offset_end");

                    b.Property<int>("SourceOffsetStart")
                        .HasColumnType("integer")
                        .HasColumnName("source_offset_start");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<string>("SourceSnippet")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_snippet");

                    b.Property<DateOnly>("VigenciaFrom")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_from");

                    b.Property<DateOnly?>("VigenciaTo")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_to");

                    b.HasKey("PowerId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_powers_document_id");

                    b.ToTable("powers", null, t =>
                        {
                            t.HasCheckConstraint("ck_powers_modo_assinatura", "modo_assinatura_tipo IN ('isolada','conjunta')");
                        });

                    b.HasData(
                        new
                        {
                            PowerId = "pw1",
                            DocumentId = "doc_001",
                            LimiteCurrency = "BRL",
                            LimiteExpression = "até R$ 500.000,00",
                            LimiteValue = 500000m,
                            ModoAssinaturaTipo = "isolada",
                            Operacao = "Movimentação financeira",
                            Pessoa = "Diretor",
                            SourceOffsetEnd = 1480,
                            SourceOffsetStart = 1280,
                            SourcePage = 4,
                            SourceSnippet = "...o Diretor poderá assinar isoladamente movimentações até R$ 500.000,00...",
                            VigenciaFrom = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            PowerId = "pw2",
                            DocumentId = "doc_001",
                            LimiteCurrency = "BRL",
                            LimiteExpression = "acima de R$ 500.000,00",
                            LimiteValue = 5000000m,
                            ModoAssinaturaM = 2,
                            ModoAssinaturaN = 2,
                            ModoAssinaturaQualificacoes = new[] { "Diretor", "Procurador" },
                            ModoAssinaturaTipo = "conjunta",
                            Operacao = "Movimentação financeira",
                            Pessoa = "Diretor + Procurador",
                            SourceOffsetEnd = 1750,
                            SourceOffsetStart = 1500,
                            SourcePage = 4,
                            SourceSnippet = "...acima desse valor, exigir-se-á assinatura conjunta de Diretor e Procurador...",
                            VigenciaFrom = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            PowerId = "pw_delta_1",
                            DocumentId = "doc_004",
                            LimiteCurrency = "BRL",
                            LimiteExpression = "até R$ 200.000,00",
                            LimiteValue = 200000m,
                            ModoAssinaturaTipo = "isolada",
                            Operacao = "Contratação de crédito",
                            Pessoa = "Titular",
                            SourceOffsetEnd = 480,
                            SourceOffsetStart = 320,
                            SourcePage = 2,
                            SourceSnippet = "...procuração com validade até 30/08/2025...",
                            VigenciaFrom = new DateOnly(2024, 1, 1),
                            VigenciaTo = new DateOnly(2025, 8, 30)
                        });
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Decision", "Decision")
                        .WithMany("AuditEvents")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Document", "Document")
                        .WithMany("AuditEvents")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Decision");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Decision", b =>
                {
                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Document", "Document")
                        .WithMany("Decisions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.KasRun", b =>
                {
                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Document", "Document")
                        .WithMany("KasRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.OutboxMessage", b =>
                {
                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Person", b =>
                {
                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Document", "Document")
                        .WithMany("Socios")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Power", b =>
                {
                    b.HasOne("BbfFirmasPoderes.Domain.Entities.Document", "Document")
                        .WithMany("Poderes")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Decision", b =>
                {
                    b.Navigation("AuditEvents");
                });

            modelBuilder.Entity("BbfFirmasPoderes.Domain.Entities.Document", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Decisions");

                    b.Navigation("KasRuns");

                    b.Navigation("Poderes");

                    b.Navigation("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
